version: "2"

run:
  timeout: 5m
  tests: false
  concurrency: 4

linters:
  default: standard
  enable:
    - funcorder
    - bodyclose
    - errorlint
    - gocritic
    - unconvert
    - misspell
    - errname
    - noctx
    - modernize

  settings:
    errcheck:
      check-type-assertions: true

formatters:
  enable:
    - gofumpt
    - golines
    - gci

  settings:
    golines:
      max-len: 120
    gofumpt:
      module-path: databasus-agent
      extra-rules: true
    gci:
      sections:
        - standard
        - default
        - localmodule
